format_version: 3
environments:
  generic:
    environment_variables:
      DOCKER_TAG: latest
      DOCKER_NO_CACHE: false
      DOCKER_BUILD_LOCAL: true
      #DOCKER_REG: docker.io
      #DOCKER_REGISTRY: docker.io
      #FROM_IMG_REGISTRY: docker.io
      #UCP_USER: test123
      #DOCKER_REGISTRY_INSECURE: true
    pipelines:
      - cv-nccl92-tf-jupyter-dev.1.12.0
pipelines:
  cv-nccl92-tf-jupyter-dev.1.12.0:
    group: cuda-9.2
    template: DockerBuild
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      git:
        git: https://github.com/qnib/uplain-pip3-jupyter
        shallow_clone: false
        auto_update: true
        branch: master
        destination: docker
      cv-nccl92-tf-dev.1.12.0:
        pipeline: cv-nccl92-tf-dev.1.12.0
        stage: DockerBuild
        name: cv-nccl92-tf-dev.1.12.0
